using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using EV2HttpExtension.Models;

namespace EV2HttpExtension.Controllers
{
    #region snippet_TodoController
    [Produces("application/json")]
    [Route("")]
    [ApiController]
    public class Ev2HttpExtensionController : ControllerBase
    {
        #endregion

        public Ev2HttpExtensionController()
        {
        }

        #region snippet_IncomingResponseHeaderCommentary
        
            /*
               Request Headers
                Ev2 will pass in the following headers when calling into an extension.

                Header  Description
                Content-Type application/json
                x-ms-request-id A unique identifier for the current operation, generated by Ev2.All extensions must return this value in the response headers to facilitate debugging.
                x-ms-client-principal-name Unique identifier of the principal performing the rollout.
                x-ms-service-group ServiceGroup name specified in Service Model for the rollout.
                x-ms-environment Environment name specified in Service Model for the rollout.
                x-ms-retry-attempt Retry attempt of current rollout.
                x-ms-resource-group Resource group of the resource the action is invoked for specified in Service Model for the rollout.
                x-ms-subscription-id Subscription Id of resource group above.
                x-ms-location Location of the resource the action is invoked for specified in Service Model for the rollout.
                x-ms-service-resource ServiceResource name of the resource the action is invoked for specified in Service Model for the rollout.
                x-ms-version Version of the api/schema used by Ev2 to call into the extension
                x-ms-usercallbackdata User callback data from the first PUT call response.
                x-ms-service-id ServiceTree id, if rollout submitted from compliant release pipeline.
            */
        #endregion

        #region snippet_Rollout
        [HttpPut("{endpoint}/Rollout/{rolloutId}/Step/{stepName}/Extension/{extensionNamespace}/{extensionType}/{extensionName}")]
        public ActionResult<ResponseBody> Execute(string endpoint, int rolloutId, string stepName, string extensionNamespace, string extensionType, string extensionName, Properties property)
        {
            return NoContent();
        }

        [HttpGet("{endpoint}/Rollout/{rolloutId}/Step/{stepName}/Extension/{extensionNamespace}/{extensionType}/{extensionName}")]
        public ActionResult<ResponseBody> QueryStatus(string endpoint, int rolloutId, string stepName, string extensionNamespace, string extensionType, string extensionName)
        {
            return NoContent();
        }

        #endregion

        #region snippet_Validate

        [HttpPut("{endpoint}/Rollout/{rolloutId}/Step/{stepName}/Extension/{extensionNamespace}/{extensionType}/{extensionName}/validate")]
        public ActionResult<ResponseBody> Validate(string endpoint, int rolloutId, string stepName, string extensionNamespace, string extensionType, string extensionName)
        {
            return NoContent();
        }

        #endregion

        #region snippet_Cancel

        [HttpPost("{endpoint}/Rollout/{rolloutId}/Step/{stepName}/Extension/{extensionNamespace}/{extensionType}/{extensionName}/cancel")]
        public ActionResult<ResponseBody> Cancel(string endpoint, int rolloutId, string stepName, string extensionNamespace, string extensionType, string extensionName)
        {
            return NoContent();
        }

        #endregion

    }
}